quality_assessment_questions:
  - id: QE1
    question: Is the methodology appropriate and adequately tailored to the specific challenges of disassembly tasks?
    scores: [0.0, 0.5, 1.0]
  - id: QE2
    question: Is the proposed robotic cell or solution described in sufficient detail to understand its functionality and application?
    scores: [0.0, 1.0, 2.0]
  - id: QE3
    question: Are the discussions of the results and conclusions thorough and well-supported by the data presented?
    scores: [0.0, 0.5, 1.0]
  - id: QE4
    question: What type of research is conducted in the work (experimental, simulation, conceptual), and is this clearly stated?
    scores: [0.0, 0.5, 1.0]
  - id: QE5
    question: Does the work’s implementation and/or the data used in the experiments are publicly available?
    scores: [0.0, 1.0]
  - id: QE6
    question: Is the proposed solution focused on disassembly tasks?
    scores: [0.0, 1.0]
  - id: QE7
    question: Does the paper present comparative results with other methods or ground-truth data to validate its findings?
    scores: [0.0, 1.0]
  - id: QE8
    question: Does the paper provide an updated review of the state of the art in the process described for disassembly tasks?
    scores: [0.0, 0.5, 1.0]

cutoff_score: 6.5

excluding_questions: [QE1, QE7, QE8]

data_extraction_fields:
  - key: TITLE
    description: Title of the paper.
  - key: PUBLISHER
    description: Name of the publisher.
  - key: AUTHOR
    description: Name of the authors that wrote the paper.
  - key: YEAR
    description: Year of publication
  - key: NUMBER OF MANIPULATORS
    description: Number of manipulators used in the study.
  - key: MANIPULATOR
    description: Model of manipulator used.
  - key: DOF OF MANIPULATOR
    description: Degrees of freedom of the manipulator used.
  - key: HARDWARE CELL COMPONENTS
    description: Components that compose the hardware of the automated cell.
  - key: SOFTWARE ARCHITECTURE COMPONENTS
    description: Algorithms that compose the software architeture of the automated cell.
  - key: VISION SYSTEM
    description: Details about the vision system used
  - key: USE OF CAD MODEL
    description: Was a CAD model used for planning, simulation, or real-time guidance?.
  - key: LEVEL OF IMPLEMENTATION
    description: Specify Technology Readiness Levels (TRL) if available or if not if it is Conceptual/Experimental/Implemented.
  - key: LEVEL OF AUTOMATION
    description: Collaborative Cell/Fully automated/Manual.
  - key: PROCESS STEPS
    description: Type of disassembly steps performed.
  - key: EFFICIENCY CONSIDERATIONS
    description: Cost/Time/Energy.
  - key: OPTIMIZATION OF DISASSEMBLY TASKS
    description: Does the study focus on optimizing any disassembly step or task?
  - key: CHALLENGES
    description: Key challenges addressed in the paper.
  - key: HOW TO
    description: How the authors achieved their goals.
  - key: RESULTS
    description: Key findings, performance metrics, and conclusions of the study.