quality_assessment_questions:
  - id: QE1
    question: Is the methodology appropriate and adequately tailored to the specific challenges of disassembly tasks, and properly validated?
    scores: [0.0, 0.5, 1.0]
  - id: QE2
    question: Is the proposed robotic cell or solution described in sufficient detail to understand its design, operation, and applicability?
    scores: [0.0, 1.0, 2.0]
  - id: QE3
    question: Are the discussions of the results and conclusions thorough and well-supported by the data presented?
    scores: [0.0, 0.5, 1.0]
  - id: QE4
    question: Is the type of research clearly specified (e.g., experimental, simulation-based, conceptual) and appropriately framed within the studys objectives?
    scores: [0.0, 0.5, 1.0]
  - id: QE5
    question: Does the work’s implementation and/or the data used in the experiments are publicly available?
    scores: [0.0, 1.0]
  - id: QE6
    question: Is the proposed solution focused on disassembly tasks?
    scores: [0.0, 1.0]
  - id: QE7
    question: Does the paper present comparative results with other methods or ground-truth data to validate its findings?
    scores: [0.0, 1.0]
  - id: QE8
    question: Does the paper provide an updated review of the state of the art of the process described in the paper, in the context of disassembly?
    scores: [0.0, 0.5, 1.0]

cutoff_score: 6.5

excluding_questions: [QE1, QE7, QE8]

data_extraction_fields:
  - key: TITLE
    description: Title of the paper.
  - key: PUBLISHER
    description: Name of the publisher.
  - key: AUTHOR
    description: Name of the authors that wrote the paper.
  - key: YEAR
    description: Year of publication
  - key: NUMBER OF MANIPULATORS
    description: Number of manipulators used in the study.
  - key: MANIPULATOR
    description: Model of manipulator used.
  - key: DOF OF MANIPULATOR
    description: Degrees of freedom of the manipulator used.
  - key: HARDWARE CELL COMPONENTS
    description: Key components of the physical robotic cell (e.g., sensors, grippers, actuators).
  - key: SOFTWARE ARCHITECTURE COMPONENTS
    description: Software frameworks, control algorithms, and architectures used.
  - key: VISION SYSTEM
    description: Details of the vision system (e.g., cameras, LiDAR, image processing techniques).
  - key: USE OF CAD MODEL
    description: Was a CAD model utilized for planning, simulation, or real-time decision-making?
  - key: LEVEL OF IMPLEMENTATION
    description: Technology Readiness Level (TRL) if specified; otherwise, categorize as Conceptual / Experimental / Implemented.
  - key: LEVEL OF AUTOMATION
    description: Define whether the system is Collaborative (Human-Robot Interaction) / Fully Automated / Manual.
  - key: PROCESS STEPS
    description: Specific disassembly operations performed (e.g., unscrewing, cutting, detaching).
  - key: ERROR RECOVERY MECHANISMS 
    description: Does the system handle failures, such as part misalignment or unexpected obstructions?
  - key: REAL-TIME FEEDBACK & CONTROL 
    description: Is there any mechanism for real-time monitoring and adjustment?
  - key: EFFICIENCY CONSIDERATIONS
    description: Factors considered in the study regarding Cost, Time, Energy Consumption.
  - key: OPTIMIZATION OF DISASSEMBLY TASKS
    description: Does the study address optimization in terms of speed, efficiency, or accuracy?
  - key: CHALLENGES
    description: Key technical and operational challenges tackled in the study.
  - key: HOW TO
    description: Explanation of how the authors achieved their goals, including techniques, strategies, and methodologies.
  - key: RESULTS
    description: Key findings, performance metrics, and conclusions drawn from the study.